projects:
  VMEmperor:
    schemaPath: app/localApi/schema.graphql
    includes:
      - "*.graphql"
    extensions:
      endpoints:
        default:
          url: 'http://localhost:3000/api/graphql'
          subscription: 'http://localhost:3000/api/subscriptions'
