version: '3'
services:
  influxdb:
    image: influxdb/influxdb
    networks:
      - influxdb
    environment:
      - INFLUXDB_DB=vmemperor

  xenservertoinflux:
    build: ./xenservertoinflux
    volumes:
      - ./configs/config.init:/app/xenservertoinflux/config.ini
    networks:
      - influxdb
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
      - xenservertoinflux
    volumes:
      - ./configs/grafana/provisioning/:/etc/grafana/provisioning
      - ./configs/grafana/public:/usr/share/grafana/public
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - influxdb
      - backend


  rethinkdb:
    image: rethinkdb:latest
    networks:
      - backend
  vmemperor:
    build: .
    volumes:
      - ./configs/config.ini:/app/config.ini
      - ./keys:/root/.ssh
    ports:
      - 8889:8889
    networks:
      - backend
    depends_on:
      - rethinkdb
      - grafana


  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

    depends_on:
      - vmemperor

networks:
  backend:
    driver: bridge
  influxdb:
    driver: bridge
