version: '3'
services:
  rethinkdb:
    image: rethinkdb:latest
    networks:
      - backend
  vmemperor:
    build: .
    volumes:
      - ./configs/login.ini:/app/login.ini
      - ./keys:/root/.ssh
    ports:
      - 8889:8889
    networks:
      - backend
    depends_on:
      - rethinkdb


  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

    depends_on:
      - vmemperor

networks:
  backend:
    driver: bridge
